server:
  error:
    include-stacktrace: on_param

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: "admin"
    password: "admin"
    url: "jdbc:h2:./toDoListBotDB"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG