spring:
  profiles:
    active:
      ${APP_ENV}
  application:
    name: to_do_list_bot

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

bot:
  name: to_do_list_bot
  token: ${BOT_TOKEN}